### ISSUE TITLE
Documentation for btn-narrow

### ISSUE THREAD

**Issue by heyallan** [basscss/base-buttons#2]
I see instances of `.btn-narrow` but I don't see any documentation about it.
Can you help?

**Comment by jxnblk** [comment]
It's part of the `btn-sizes` module: https://github.com/basscss/btn-sizes

**Comment by heyallan** [comment]
I don't find any particular css related to it.
There is no `.button-narrow` in css (?)
`.button-narrow` has no effect IFAIK.

**Comment by heyallan** [comment]
Nor, `.button-big`, nor `.button-small`

**Comment by heyallan** [comment]
Please review: http://www.basscss.com/docs/guides/ui/#button-sizes
Nor `.button-big, .button-narrow, .button-small` have any effect on buttons:

![screen shot 2015-12-09 at 10 17 34](https://cloud.githubusercontent.com/assets/1783777/11690932/7a090e26-9e5e-11e5-9ac6-b1cf498ca920.png)

**Comment by heyallan** [comment]
Found 2 different nomenclatures (?):
`.btn-X`: https://github.com/basscss/btn-sizes/blob/master/index.css
`.button-X`: http://www.basscss.com/docs/guides/ui/#button-sizes
None of them have any effect.

**Comment by jxnblk** [comment]
Yeah, that's a typo. The most recent button modules use the `btn` naming convention. The guide probably doesn't pull in the `btn-sizes` module. Most of the guides need a review and updates.

**Comment by heyallan** [comment]
:+1:
